from __future__ import annotations

from app.schemas import CandidateProfile


SEED_CANDIDATES: list[CandidateProfile] = [
    CandidateProfile(
        id="cand_001",
        name="Aarav Menon",
        headline="Senior AI Platform Engineer",
        location="Bengaluru, IN",
        education=["MS Computer Science, IIIT Hyderabad"],
        skills=[
            "LLMs",
            "RAG",
            "LangChain",
            "Pinecone",
            "MLOps",
            "CUDA",
            "GPU Optimization",
            "Kubernetes",
            "FastAPI",
        ],
        projects=[
            "Built production RAG search for 30M technical documents",
            "Reduced GPU inference cost by 42 percent with quantization and batching",
        ],
        certifications=["AWS Machine Learning Specialty", "NVIDIA Deep Learning Institute CUDA"],
        resume_text="Led AI platform team shipping LLM deployment, vector search, monitoring, and evaluation pipelines.",
        experience_years=7,
        career_metadata={
            "job_switches": 2,
            "promotion_velocity": 0.85,
            "company_quality": 0.9,
            "leadership_roles": ["Tech Lead", "Mentor"],
            "team_size": 8,
            "industries": ["Artificial Intelligence", "SaaS"],
        },
        activity_signals={
            "github_commits_12m": 612,
            "github_stars": 940,
            "open_source_contributions": 18,
            "kaggle_medals": 1,
            "hackathons": 3,
            "blog_posts": 6,
            "forum_answers": 34,
            "recent_certifications": 2,
            "new_skills_added": 5,
        },
        social_signals={"mentorship": True, "conference_talks": 3, "technical_writing": True},
    ),
    CandidateProfile(
        id="cand_002",
        name="Maya Iyer",
        headline="Principal Data Scientist, Search and Ranking",
        location="Mumbai, IN",
        education=["PhD Machine Learning, IISc"],
        skills=[
            "Learning to Rank",
            "LightGBM",
            "XGBoost",
            "BGE Embeddings",
            "Sentence Transformers",
            "Weaviate",
            "MLOps",
            "Experimentation",
        ],
        projects=[
            "Designed semantic retrieval and reranking stack for recruiting search",
            "Launched online model evaluation and drift monitoring platform",
        ],
        certifications=["Coursera Deep Learning Specialization"],
        resume_text="Strong ranking, embeddings, retrieval, and experimentation background with cross-functional leadership.",
        experience_years=9,
        career_metadata={
            "job_switches": 1,
            "promotion_velocity": 0.7,
            "company_quality": 0.92,
            "leadership_roles": ["Principal IC", "Hiring Panel Lead"],
            "team_size": 5,
            "industries": ["HR Tech", "Search"],
        },
        activity_signals={
            "github_commits_12m": 180,
            "github_stars": 270,
            "open_source_contributions": 4,
            "kaggle_medals": 4,
            "hackathons": 1,
            "blog_posts": 9,
            "forum_answers": 61,
            "recent_certifications": 1,
            "new_skills_added": 3,
        },
        social_signals={"mentorship": True, "conference_talks": 5, "technical_writing": True},
    ),
    CandidateProfile(
        id="cand_003",
        name="Rohan Kapoor",
        headline="Machine Learning Engineer",
        location="Delhi, IN",
        education=["BTech Computer Science, DTU"],
        skills=["Python", "PyTorch", "Docker", "FastAPI", "PostgreSQL", "Airflow", "Model Serving"],
        projects=[
            "Built fraud model serving API",
            "Maintained ML training workflows and feature pipelines",
        ],
        certifications=["Google Professional Data Engineer"],
        resume_text="ML engineer with model serving, data pipelines, and backend API experience.",
        experience_years=4,
        career_metadata={
            "job_switches": 3,
            "promotion_velocity": 0.45,
            "company_quality": 0.64,
            "leadership_roles": [],
            "team_size": 0,
            "industries": ["Fintech"],
        },
        activity_signals={
            "github_commits_12m": 95,
            "github_stars": 32,
            "open_source_contributions": 0,
            "kaggle_medals": 0,
            "hackathons": 1,
            "blog_posts": 0,
            "forum_answers": 8,
            "recent_certifications": 1,
            "new_skills_added": 2,
        },
        social_signals={"mentorship": False, "conference_talks": 0, "technical_writing": False},
    ),
    CandidateProfile(
        id="cand_004",
        name="Nisha Rao",
        headline="Staff MLOps Engineer",
        location="Hyderabad, IN",
        education=["MS Data Engineering, Georgia Tech"],
        skills=[
            "MLOps",
            "Kubernetes",
            "Docker",
            "Ray",
            "GPU Optimization",
            "Triton Inference Server",
            "Terraform",
            "Prometheus",
        ],
        projects=[
            "Scaled GPU inference platform across six regions",
            "Built CI/CD and observability for ML models",
        ],
        certifications=["Certified Kubernetes Administrator"],
        resume_text="Staff MLOps engineer focused on deployment reliability, model serving, and GPU infrastructure.",
        experience_years=10,
        career_metadata={
            "job_switches": 2,
            "promotion_velocity": 0.78,
            "company_quality": 0.88,
            "leadership_roles": ["Staff Engineer", "Architecture Review Board"],
            "team_size": 6,
            "industries": ["Cloud Infrastructure", "Artificial Intelligence"],
        },
        activity_signals={
            "github_commits_12m": 330,
            "github_stars": 510,
            "open_source_contributions": 11,
            "kaggle_medals": 0,
            "hackathons": 0,
            "blog_posts": 4,
            "forum_answers": 45,
            "recent_certifications": 1,
            "new_skills_added": 4,
        },
        social_signals={"mentorship": True, "conference_talks": 2, "technical_writing": True},
    ),
    CandidateProfile(
        id="cand_005",
        name="Kabir Sethi",
        headline="NLP Research Engineer",
        location="Pune, IN",
        education=["MS AI, University of Edinburgh"],
        skills=[
            "LLMs",
            "Fine Tuning",
            "Prompt Engineering",
            "Embedding Models",
            "Transformers",
            "PyTorch",
            "Evaluation",
        ],
        projects=[
            "Fine-tuned domain LLMs for legal document analysis",
            "Published benchmark for retrieval augmented QA",
        ],
        certifications=[],
        resume_text="Research engineer with LLM fine tuning, embeddings, evaluation, and publication track record.",
        experience_years=5,
        career_metadata={
            "job_switches": 1,
            "promotion_velocity": 0.52,
            "company_quality": 0.76,
            "leadership_roles": ["Research Mentor"],
            "team_size": 3,
            "industries": ["Legal Tech", "Artificial Intelligence"],
        },
        activity_signals={
            "github_commits_12m": 220,
            "github_stars": 780,
            "open_source_contributions": 7,
            "kaggle_medals": 0,
            "hackathons": 2,
            "blog_posts": 11,
            "forum_answers": 19,
            "recent_certifications": 0,
            "new_skills_added": 4,
            "patents": 0,
            "research_papers": 3,
        },
        social_signals={"mentorship": True, "conference_talks": 2, "technical_writing": True},
    ),
    CandidateProfile(
        id="cand_006",
        name="Ishita Das",
        headline="Backend Engineer, Data Products",
        location="Kolkata, IN",
        education=["BTech Information Technology, Jadavpur University"],
        skills=["FastAPI", "PostgreSQL", "Redis", "Next.js", "Docker", "Search APIs", "ETL"],
        projects=[
            "Built recruiter workflow APIs and dashboards",
            "Implemented profile ingestion and resume parsing services",
        ],
        certifications=[],
        resume_text="Backend engineer with strong data product and API delivery experience.",
        experience_years=6,
        career_metadata={
            "job_switches": 2,
            "promotion_velocity": 0.61,
            "company_quality": 0.58,
            "leadership_roles": ["Module Owner"],
            "team_size": 2,
            "industries": ["HR Tech"],
        },
        activity_signals={
            "github_commits_12m": 260,
            "github_stars": 65,
            "open_source_contributions": 1,
            "kaggle_medals": 0,
            "hackathons": 0,
            "blog_posts": 2,
            "forum_answers": 12,
            "recent_certifications": 0,
            "new_skills_added": 1,
        },
        social_signals={"mentorship": False, "conference_talks": 0, "technical_writing": True},
    ),
    CandidateProfile(
        id="cand_007",
        name="Dev Patel",
        headline="AI Product Engineer",
        location="Ahmedabad, IN",
        education=["BS Computer Science, Ashoka University"],
        skills=[
            "RAG",
            "LangChain",
            "OpenAI",
            "Qdrant",
            "Prompt Engineering",
            "Next.js",
            "FastAPI",
            "PostgreSQL",
        ],
        projects=[
            "Shipped AI copilot for sales teams using Qdrant and OpenAI",
            "Built prompt evaluation and feedback workflow",
        ],
        certifications=["OpenAI API Bootcamp"],
        resume_text="Product-minded engineer building end-to-end AI copilots and retrieval experiences.",
        experience_years=4.5,
        career_metadata={
            "job_switches": 1,
            "promotion_velocity": 0.66,
            "company_quality": 0.7,
            "leadership_roles": ["Founding Engineer"],
            "team_size": 4,
            "industries": ["B2B SaaS", "Artificial Intelligence"],
        },
        activity_signals={
            "github_commits_12m": 540,
            "github_stars": 390,
            "open_source_contributions": 5,
            "kaggle_medals": 0,
            "hackathons": 5,
            "blog_posts": 5,
            "forum_answers": 25,
            "recent_certifications": 1,
            "new_skills_added": 6,
        },
        social_signals={"mentorship": True, "conference_talks": 1, "technical_writing": True},
    ),
    CandidateProfile(
        id="cand_008",
        name="Sara Thomas",
        headline="Data Science Manager",
        location="Chennai, IN",
        education=["MBA Analytics, ISB", "BSc Statistics, Loyola College"],
        skills=["Leadership", "Experimentation", "Forecasting", "Stakeholder Management", "SQL", "Python"],
        projects=[
            "Managed analytics roadmap for marketplace growth",
            "Coached team of seven analysts and data scientists",
        ],
        certifications=["Product Analytics Certification"],
        resume_text="Data science leader with strong stakeholder management and people leadership.",
        experience_years=11,
        career_metadata={
            "job_switches": 2,
            "promotion_velocity": 0.74,
            "company_quality": 0.8,
            "leadership_roles": ["Manager", "Mentor", "Hiring Manager"],
            "team_size": 7,
            "industries": ["Marketplace", "Consumer Internet"],
        },
        activity_signals={
            "github_commits_12m": 25,
            "github_stars": 5,
            "open_source_contributions": 0,
            "kaggle_medals": 0,
            "hackathons": 0,
            "blog_posts": 3,
            "forum_answers": 4,
            "recent_certifications": 1,
            "new_skills_added": 2,
        },
        social_signals={"mentorship": True, "conference_talks": 4, "technical_writing": True},
    ),
]
